# Generated by Django 5.1.6 on 2025-02-23 06:59

import common.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, default=common.models.generate_code, editable=False, max_length=8, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='files/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('presigned_url', models.URLField(blank=True, null=True)),
                ('presigned_upload_complete', models.BooleanField(default=None, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
