from os import getenv

# AWS
AWS_ACCESS_KEY_ID = getenv("AWS_ACCESS_KEY_ID")
AWS_SECRET_ACCESS_KEY = getenv("AWS_SECRET_ACCESS_KEY")

# AWS S3
AWS_STORAGE_BUCKET_NAME = getenv("AWS_STORAGE_BUCKET_NAME")
AWS_S3_REGION_NAME = getenv("AWS_S3_REGION_NAME")
AWS_S3_ENDPOINT_URL = getenv("AWS_S3_ENDPOINT_URL")
AWS_S3_SIGNATURE_VERSION = getenv("AWS_S3_SIGNATURE_VERSION", default="s3v4")
AWS_DEFAULT_ACL = getenv("AWS_DEFAULT_ACL", default="private")
AWS_PRESIGNED_EXPIRE = int(getenv("AWS_PRESIGNED_EXPIRE", default="30"))  # seconds
