# Generated by Django 5.1.6 on 2025-03-04 07:47

from django.db import migrations
from pgvector.django import VectorExtension


class Migration(migrations.Migration):
    operations = [VectorExtension()]
